language: java
jdk:
  - oraclejdk8
  - openjdk8
  
os:
  - linux
  
if: tag IS blank

install: "gradle setupCIWorkspace"
script: "gradle build"

before_deploy:
  - export GIT_TAG=$TRAVIS_BRANCH-0.1-build$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER."
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file_glob: true
  file: 
    - "build/libs/jsonmod-*.jar"
  skip_cleanup: true
  on:
    jdk: oraclejdk8
    tags: false